---
- hosts: localhost
  gather_facts: false

  collections:
    - ansible.posix 
    - community.general
    - portfoliossa.nsupdate

  tasks:
#    - name: debug current role path
#      debug:
#        msg: |
#          roles_path: {{ roles_path }}
#      when:
#        - debug | default ('false') | bool
#
    - name: include nsupdate
      ansible.builtin.include_role: 
        name: portfoliossa.nsupdate.nsupdate
      vars:
        record: "{{ item.record }}"
        value:  "{{ item.value }}"
        rrtype: "{{ item.rrtype }}"
        instruction: "{{ item.instruction }}"
        nameserver: "{{ item.nameserver }}"
      loop: "{{ bastion_named_records }}"
