---
- hosts: uc1_targets
  gather_facts: false

  collections:
    - hpe.oneview
  tasks:
    - name: configure physical hosts via oneview
      ansible.builtin.include_role:
        name: portfoliossa.bcl.oneview_config
