---
- hosts: vcenter
  gather_facts: false

  collections:
    - vmware.vmware_rest
    - community.vmware

  tasks:
    - name: prepare and configure vcenter
      ansible.builtin.include_role:
        name: portfoliossa.bcl.vcenter_prepare
      vars:
        vcenter_hostname: "{{ bclvmw_host }}"
        vcenter_username: "{{ bclvmw_username }}"
        vcenter_password: "{{ bclvmw_password }}"
        vcenter_validate_certs: "{{ bclvmw_validate_certs }}"
        vcenter_datacentername: '{{ bclvmw_datacentername }}'

      when: bclvmw_enable | default ('false') | bool
