---
- hosts: esx_hosts
  gather_facts: false
  serial: 1

  collections:
    - hpe.oneview
    - ansible.posix 

  tasks:
  - name: install esxi on bare metal nodes
    ansible.builtin.include_role:
      name: mschreie.bcl.vmware-iso-boot
    when: bclvmw_enable | default ('false') | bool
