---
- name: Add a Server Hardware to Oneview
  hpe.oneview.oneview_server_hardware:
    hostname: "{{ oneview_host }}"
    username: "{{ oneview_username }}"
    password: "{{ oneview_password }}"
    auth_login_domain: "{{ oneview_domain }}"
    api_version: "{{ oneview_apiversion }}"

    state: present
    data:
      hostname : "{{ ilo_ip}}"
      username : "{{ ilo_username }}"
      password : "{{ ilo_password }}"
      force : false
      licensingIntent: "OneView"
      configurationState: "Managed"
  delegate_to: localhost
  ignore_errors: true
      
- name: Switch Server off
  hpe.oneview.oneview_server_hardware:
    hostname: "{{ oneview_host }}"
    username: "{{ oneview_username }}"
    password: "{{ oneview_password }}"
    auth_login_domain: "{{ oneview_domain }}"
    api_version: "{{ oneview_apiversion }}"

    state: power_state_set
    data:
      name : "{{ inventory_hostname }}.hpintelco.org"
      powerStateData:
        powerState: "Off"
        powerControl: "MomentaryPress"
  delegate_to: localhost
  ignore_errors: true
      
- name: Create a server profile 
  hpe.oneview.oneview_server_profile:
    hostname: "{{ oneview_host }}"
    username: "{{ oneview_username }}"
    password: "{{ oneview_password }}"
    auth_login_domain: "{{ oneview_domain }}"
    api_version: "{{ oneview_apiversion }}"

    state: present
    data:
      "{{ lookup('ansible.builtin.template', 'server_profile_template.j2') | from_yaml }}"
    params:
      force: true
  delegate_to: localhost
  register: result

- debug: msg= "{{ result.msg }}"

##- name: Gather facts about the Server Profile Template by name
##  hpe.oneview.oneview_server_profile_template_facts:
##    hostname: "{{ oneview_host }}"
##    username: "{{ oneview_username }}"
##    password: "{{ oneview_password }}"
##    auth_login_domain: "{{ oneview_domain }}"
##    api_version: "{{ oneview_apiversion }}"
##
##    name: "{{ server_profile_template_name }}"
##  delegate_to: localhost
##
##- debug: var=server_profile_templates
